\set ON_ERROR_STOP on

SET search_path TO id_benchmark, public;

CREATE TABLE event_log_uuid (
    id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
    tenant_id integer NOT NULL,
    actor_id bigint NOT NULL,
    event_type text NOT NULL,
    created_at timestamptz NOT NULL DEFAULT now(),
    payload jsonb NOT NULL
);

CREATE INDEX event_log_uuid_tenant_created_idx
    ON event_log_uuid (tenant_id, created_at DESC);

CREATE INDEX event_log_uuid_type_created_idx
    ON event_log_uuid (event_type, created_at DESC);

CREATE TABLE event_note_uuid (
    id BIGSERIAL PRIMARY KEY,
    event_id uuid NOT NULL REFERENCES event_log_uuid (id) ON DELETE CASCADE,
    note_type text NOT NULL,
    created_at timestamptz NOT NULL DEFAULT now(),
    body text NOT NULL
);

CREATE INDEX event_note_uuid_event_id_idx
    ON event_note_uuid (event_id);

COMMENT ON TABLE event_log_uuid IS
    'Event log variant with random UUID primary key generated by PostgreSQL.';

COMMENT ON TABLE event_note_uuid IS
    'Child table used to show how UUID width affects foreign keys and their indexes.';
